In [1]:
import numpy as np

In [3]:
b = np.array([1, 2, 3, 4])

b = b*2

b

array([2, 4, 6, 8])

## Numpy Demo

In [11]:
a = np.arange(1, 10, 2.5)
a

array([1. , 3.5, 6. , 8.5])

In [12]:
type(a)

numpy.ndarray

In [21]:
b = np.arange(1, 1369)
b

array([   1,    2,    3, ..., 1366, 1367, 1368])

In [23]:
b = b.reshape(-1, 2)

In [24]:
b.shape

(684, 2)

In [25]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [26]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a = a.astype('float32')
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [33]:
a = np.array([[1,2], [3,4], [5,6], [7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
a[0][0]

1

In [31]:
a[1]

array([3, 4])

In [36]:
a[1:, 1]

array([4, 6, 8])

In [37]:
'''
1D -> Vector
2D -> Matrix
3D -> Tensor

'''

'\n1D -> Vector\n2D -> Matrix\n3D -> Tensor\n\n'

### Tensor

In [79]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
c[-2][-2][-3]

5

In [40]:
c[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [47]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [48]:
a<3

array([ True,  True, False, False, False])

In [50]:
a[a<=3]

array([1, 2, 3])

In [89]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [90]:
b= np.arange(5, 10)


In [91]:
b

array([5, 6, 7, 8, 9])

In [93]:
a*b

array([ 5, 12, 21, 32, 45])

In [54]:
a.dot(b)

115

In [55]:
b.dot(a)

115

In [58]:
b.T

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

In [76]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
b = a.reshape(5,6)

In [71]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [77]:
a = a.reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [80]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Special Arrays

In [82]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
a = np.zeros(5)

In [87]:
b = np.ones(5)

In [88]:
a+b

array([1., 1., 1., 1., 1.])

In [94]:
np.empty((4,5))

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.02359984e-306, 7.56599807e-307],
       [7.56587585e-307, 7.56593017e-307, 1.24610383e-306,
        1.24610723e-306, 1.37962320e-306],
       [1.29060871e-306, 2.22522597e-306, 1.33511969e-306,
        1.78022342e-306, 1.05700345e-307],
       [1.11261027e-306, 1.33512376e-306, 9.34609790e-307,
        7.23188049e-308, 8.49820789e+183]])

In [95]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.linspace(1, 90, 9)

array([ 1.   , 12.125, 23.25 , 34.375, 45.5  , 56.625, 67.75 , 78.875,
       90.   ])

### Analysis

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a.sum()

66

In [4]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b.sum()

66

In [6]:
'''
Axis
0 -> Rows
1 -> Columns
'''

'\nAxis\n0 -> Rows\n1 -> Columns\n'

In [7]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [8]:
b.sum(axis=1)

array([ 6, 22, 38])

In [9]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
c.sum(axis=0) # 1 & 2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [11]:
c.sum(axis = 1) # 0 and 2

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [12]:
c.sum(axis = 2) # 0 and 1

array([[ 6, 22, 38],
       [54, 70, 86]])

In [13]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
b.max(axis=0)

array([ 8,  9, 10, 11])

In [17]:
b.mean(axis=1)

array([1.5, 5.5, 9.5])

In [18]:
np.median(b)

5.5

In [19]:
np.std(b)

3.452052529534663

### Random Distributions

In [35]:
50 + np.random.randint(4,10)*10

130

In [65]:
np.random.seed(32)
np.random.randint(2,5, 5)

array([3, 4, 2, 4, 2])

In [53]:
np.random.seed(32)
np.random.randint(10,743)

737

In [61]:
np.random.rand(4,5)

array([[0.28525734, 0.76598159, 0.82705909, 0.03879199, 0.31330032],
       [0.8882369 , 0.84822129, 0.70954671, 0.76456265, 0.14569192],
       [0.52152528, 0.3649881 , 0.99561742, 0.42428175, 0.9731956 ],
       [0.45226329, 0.37549535, 0.00129834, 0.18121861, 0.83290541]])

In [73]:
mu = 100
sigma = 15
a = np.random.normal(mu, sigma, 5000)

In [74]:
np.mean(a)

99.79079177711708

In [75]:
np.std(a)

14.916355068540508

In [87]:
a = np.random.randint(5,17, 7) 

In [88]:
a

array([ 8,  7, 13, 14, 13,  6, 16])

In [89]:
np.sort(a, axis=-1)

array([ 6,  7,  8, 13, 13, 14, 16])

In [84]:
np.random.normal?

In [90]:
np.sort?