In [2]:
import numpy as np

In [3]:
b = np.array([1, 2, 3, 4])

b = b*2

b

array([2, 4, 6, 8])

## Numpy Demo

In [11]:
a = np.arange(1, 10, 2.5)
a

array([1. , 3.5, 6. , 8.5])

In [12]:
type(a)

numpy.ndarray

In [21]:
b = np.arange(1, 1369)
b

array([   1,    2,    3, ..., 1366, 1367, 1368])

In [23]:
b = b.reshape(-1, 2)

In [24]:
b.shape

(684, 2)

In [25]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [26]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a = a.astype('float32')
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [33]:
a = np.array([[1,2], [3,4], [5,6], [7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
a[0][0]

1

In [31]:
a[1]

array([3, 4])

In [36]:
a[1:, 1]

array([4, 6, 8])

In [37]:
'''
1D -> Vector
2D -> Matrix
3D -> Tensor

'''

'\n1D -> Vector\n2D -> Matrix\n3D -> Tensor\n\n'

### Tensor

In [79]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
c[-2][-2][-3]

5

In [40]:
c[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [47]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [48]:
a<3

array([ True,  True, False, False, False])

In [50]:
a[a<=3]

array([1, 2, 3])

In [89]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [90]:
b= np.arange(5, 10)


In [91]:
b

array([5, 6, 7, 8, 9])

In [93]:
a*b

array([ 5, 12, 21, 32, 45])

In [54]:
a.dot(b)

115

In [55]:
b.dot(a)

115

In [58]:
b.T

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

In [76]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
b = a.reshape(5,6)

In [71]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [77]:
a = a.reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [80]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Special Arrays

In [82]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
a = np.zeros(5)

In [87]:
b = np.ones(5)

In [88]:
a+b

array([1., 1., 1., 1., 1.])

In [94]:
np.empty((4,5))

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.02359984e-306, 7.56599807e-307],
       [7.56587585e-307, 7.56593017e-307, 1.24610383e-306,
        1.24610723e-306, 1.37962320e-306],
       [1.29060871e-306, 2.22522597e-306, 1.33511969e-306,
        1.78022342e-306, 1.05700345e-307],
       [1.11261027e-306, 1.33512376e-306, 9.34609790e-307,
        7.23188049e-308, 8.49820789e+183]])

In [95]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.linspace(1, 90, 9)

array([ 1.   , 12.125, 23.25 , 34.375, 45.5  , 56.625, 67.75 , 78.875,
       90.   ])